//
//  main.m
//  Problem 2
//
//  Created by Robert De Guzman on 9/24/14.
//
//

/*
 Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 
 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 
 By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */

#import <Foundation/Foundation.h>

int main(int argc, const char * argv[])
{
    int first = 1;
    int second = 2;
    int sum = 2;
    int next = 0;
    
    NSLog(@"%i", first);
    NSLog(@"%i", second);
    for (int i = 0; next < 4000000; i++)
    {
        next = first + second;

        if(next > 4000000)
        {
            NSLog(@"Next");
            break;
        }

        if(next%2 == 0)
        {
            NSLog(@"adding %i",next);
            sum += next;
        }

        first = second;
        second = next;

    }
    
    NSLog(@"Sum: %i",sum);
    return 0;
}

